openapi: 3.0.0
info:
  title: Example Open API Documentation
  version: 1.0.0
  description: >
    Documentation example. You can add various kinds of **documentation** here.
    It takes both markdown and HTML

    <h2> ER Diagram </h2>

    <img
    src=
    />

    <h2> Error Codes </h2>

    <table>
      <thead>
        <th> Resource </th>
        <th> Error Code </th>
        <th> Message </th>
      </thead>
      <tbody>
        <tr>
          <td> Resource </td>
          <td> Error Code </td>
          <td> Message </td>
        </tr>
      </tbody>
    </table>
servers:
  - url: http://127.0.0.1:8080/
        
paths:
  /api/user/{username}:
                      description: >-
                        end point to read, update and delete a user resource with username
                      get:
                        description: Operation to get a user details
                        parameters:
                          - in: path
                            name: username
                            required: true
                            schema:
                              type: string
                              example: ali
                        responses:
                          '200':
                            description: Success
                            content:
                              application/json:
                                schema:
                                  title: user object
                                  type: object
                                  properties:
                                    username:
                                      type: string
                                      example: ali
                                    email:
                                      type: string
                                      example: ali@example.com
                          '400':
                            description: Bad Request.
                            content: 
                              application/json:
                                schema:
                                  type: object
                                  properties:
                                    error_code:
                                      type: string
                                    error_message:
                                      type: string
                          '404':
                            description: Resource not found.
                          '500':
                            description: Internal Server Error.
                      put:
                        description: Operation to update the user detail
                        parameters:
                          - in: path
                            name: username
                            required: true
                            schema:
                              type: string
                              example: ali
                        requestBody:
                          content:
                            application/json:
                              schema:
                                type: object
                                properties:
                                  email:
                                    type: string
                                    example: ali@example2.org
                        responses:
                          '200':
                            description: Succesfully updated.
                            content: 
                              application/json:
                                schema:
                                  title: user object
                                  type: object
                                  properties:
                                    username:
                                      type: string
                                      example: ali
                                    email:
                                      type: string
                                      example: ali@example2.com
                          '400':
                            description: Bad Request.
                            content: 
                              application/json:
                                schema:
                                  type: object
                                  properties:
                                    error_code:
                                      type: string
                                    error_message:
                                      type: string
                          '404':
                            description: Resource you requested to update not found
                          '500':
                            description: Internal Server Error
                      delete:
                        description: Operation to delete the user.
                        parameters:
                          - in: path
                            name: username
                            required: true
                            schema:
                              type: string
                              example: raj
                        responses:
                          '200':
                            description: Successfully deleted
                          '400':
                            description: Bad Request
                            content:
                              application/json:
                                schema:
                                  type: object
                                  properties:
                                    error_code:
                                      type: string
                                    error_message:
                                      type: string
                          '404':
                            description: User does not exist
                          '500':
                            description: Internal Server Error
  /api/user:
            description: end point to create a user
            post:
              description: operation to create a user
              requestBody:
                content:
                  application/json:
                    schema:
                      title: user Object
                      type: object
                      properties:
                        email:
                          type: string
                          example: raj@example.com
                        first_name:
                          type: string
                          example: raj
                        last_name:
                          type: string
                          example: sharma
                        username:
                          type: string
                          example: raj
                        password:
                          type: string
                          example: secret
                        repeat_password:
                          type: string
                          example: secret
              responses:
                '201':
                description: Successfully created
                '400':
                  description: Bad Request
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          error_code:
                            type: string
                          error_message:
                            type: string
                '409':
                  description: Username already exists
                '500':
                  description: Internal Server Error      
                  
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                                      
                          
                                      
                                
                                
                      
      
